CREATE TABLE Productos (
    ProductoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Descripcion CLOB,
    Precio NUMBER(10, 2),
    Categoria VARCHAR2(50),
    Tamano VARCHAR2(50),
    ColoresDisponibles VARCHAR2(255)
);

select * from Productos;

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Clarks Tilden Cap', 'Zapato Oxford clásico de cuero, ideal para ocasiones formales.', 4500.00, 'Zapatos Formales', '40, 41, 42, 43, 44', 'Negro, Marrón');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Vans Authentic', 'Las clásicas zapatillas de lona, sencillas y cómodas para el día a día.', 2200.00, 'Zapatos Casuales', '40, 41, 42, 43', 'Negro, Azul Marino, Rojo');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Nike Air Max 270', 'Zapatillas deportivas con excelente amortiguación, ideales para actividades deportivas.', 5500.00, 'Zapatillas Deportivas', '40, 41, 42, 43, 44', 'Negro, Blanco, Gris');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Dr. Martens 1460', 'Botines de cuero con 8 ojales, ideales para un look robusto y duradero.', 7500.00, 'Botines', '40, 41, 42, 43', 'Negro, Marrón');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Nike Benassi JDI', 'Sandalias cómodas de plástico, ideales para después del gimnasio o uso casual.', 1500.00, 'Sandalias', '40, 41, 42, 43', 'Negro, Blanco, Azul');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Sperry Top-Sider Authentic Original', 'Mocasines náuticos de cuero, perfectos para ocasiones informales pero elegantes.', 4000.00, 'Mocasines', '40, 41, 42, 43', 'Marrón, Azul Marino');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Timberland 6-Inch Premium Waterproof Boot', 'Botas resistentes al agua de cuero, ideales para el invierno o actividades al aire libre.', 8000.00, 'Botas', '40, 41, 42, 43', 'Amarillo, Marrón');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Cole Haan Pinch Tassel Loafer', 'Mocasín de lujo de cuero, ideal para trabajo o eventos formales.', 7000.00, 'Zapatos de Oficina', '40, 41, 42, 43', 'Marrón, Negro');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Allen Edmonds Park Avenue', 'Zapato Oxford de cuero, perfecto para ocasiones formales como bodas y reuniones de trabajo.', 9000.00, 'Zapatos de Cuero', '40, 41, 42, 43', 'Negro, Marrón');

INSERT INTO Productos (Nombre, Descripcion, Precio, Categoria, Tamano, ColoresDisponibles)
VALUES ('Salvatore Ferragamo F-Flag Loafer', 'Zapatos de charol de lujo, ideales para ocasiones especiales como bodas o cenas de gala.', 15000.00, 'Zapatos de Noche', '40, 41, 42, 43', 'Negro, Marrón');
